name: linux

on:
  push:
    branches: ['*']
    tags-ignore: ['*']
  pull_request:
  
env: 
  DEBIAN_FRONTEND: noninteractive
  CPAN_MIRROR: http://www.cpan.org
  VERBOSE: '' # --verbose
  # Makefile.PL is a fake care of Module::Build::Compat version 0.4224
  # it explodes about missing manifests, and if you create it, it freaks out about: 
  #   Could not add META.yml to MANIFEST: Could not open MANIFEST: No such file or directory at /usr/local/lib/perl5/5.26.3/ExtUtils/Manifest.pm line 723.
  NO_META: 1 
     
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
# this matrix is repeated in other build steps.
        perl-version: 
          - '5.26' # first with PERL_USE_UNSAFE_INC 
          - '5.36'
          
    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v3
      
      - name: apt-get
        run:  apt-get update && apt-get install -y make gcc libssl-dev libnet-ssleay-perl
        
      - name: git config
        run: |
            git config --global user.email "im-sorry-my-ci-build-is-harssing-you-from@cryt-le.github.com"; 
            git config --global user.name "CI build of $GITHUB_REF";
            git config --global safe.directory '*'; # this is a security feature 
            
      - name: Makefile.PL make dist
        env:
          PERL_USE_UNSAFE_INC: 1 
#            make test TEST_VERBOSE=1  ;
        run: |
            perl Makefile.PL && make manifest  ; 
            make dist  ;

      - name: cpanm install 
        env:
          PERL_USE_UNSAFE_INC: 1 
        run: |
            mkdir scratch && cp Crypt-LE*gz scratch/ && cd scratch/ && cpanm -L lib ./Crypt-LE*gz
            
      - name: debug artifact
        uses: actions/upload-artifact@v4
        with:
          path: Crypt-LE*gz 
