name: linux

on:
  push:
    branches: ['*']
    tags-ignore: ['*']
  pull_request:
  
env: 
  DEBIAN_FRONTEND: noninteractive
  CPAN_MIRROR: http://www.cpan.org
  VERBOSE: '' # --verbose
     
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
# this matrix is repeated in other build steps.
        perl-version: 
          - '5.26' # first with PERL_USE_UNSAFE_INC 
          - '5.36'
          
    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v3
      
      - name: apt-get
        run:  apt-get update && apt-get install -y make gcc libssl-dev libnet-ssleay-perl
        
      - name: git config
        run: |
            git config --global user.email "im-sorry-my-ci-build-is-harssing-you-from@cryt-le.github.com"; 
            git config --global user.name "CI build of $GITHUB_REF"
            
      - name: Makefile.PL
        env:
          PERL_USE_UNSAFE_INC: 1 
        run: |
            git ls-files | grep -v .github > MANIFEST 
            perl Makefile.PL && make dist 
            mkdir scratch && cd scratch/ && mv ../Crypt-LE*gz . && cpanm install ./Crypt-LE*gz

